# Generated by Django 4.1.5 on 2023-02-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
